### ISSUE TITLE
Second occurrence of "correct character, wrong position" isn't reported

### ISSUE THREAD

**Issue by manimino** [will2dye4/wordye#1]
![image](https://user-images.githubusercontent.com/76219068/150575079-0ad4beb5-754a-4096-9ddc-3e66afe6e17e.png)

In the 1/6 line both T's and O's should be yellow.

**Comment by will2dye4** [comment]
This is fixed @ [66aa441](https://github.com/will2dye4/wordye/commit/66aa441b3beeea00f1f37a8d521c5a3df292a201).
